# NumPyとPandasのトレーニング♨

## 参考
開発基盤部会 Wiki
- NumPy  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?NumPy
- Pandas  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?Pandas

## 準備

### インストール

In [39]:
!pip install numpy
!pip install pandas

### インポート

In [2]:
import numpy as np
import pandas as pd

## 配列操作
配列はベクトルとも呼ばれる。

### 生成

#### array

In [26]:
x=np.array([1.0,2.0,3.0])
x

array([1., 2., 3.])

#### arange

In [27]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ones（一埋

In [28]:
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### zeros（零埋

In [29]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### ランダム

##### empty

In [31]:
x=np.empty(5)
x

array([4.68122349e-310, 0.00000000e+000, 4.68122349e-310, 4.68122344e-310,
       2.37151510e-322])

##### random.randn（標準正規分布

In [32]:
x=np.random.randn(10)
x

array([-0.27301223, -0.38199538, -0.71194393, -0.04404173,  0.61495555,
        1.35759679, -0.06047152,  0.24681301, -1.22381463, -1.46069575])

#### 表示

##### 生

In [33]:
x

array([-0.27301223, -0.38199538, -0.71194393, -0.04404173,  0.61495555,
        1.35759679, -0.06047152,  0.24681301, -1.22381463, -1.46069575])

##### print

In [38]:
print(x)

NameError: name 'x' is not defined

##### その他の関数

###### type (型

In [39]:
type(x)

NameError: name 'x' is not defined

###### ndim (配列の次元は１次元

In [36]:
np.ndim(x)

1

###### shape (次元の形状

In [37]:
x.shape

(10,)

###### shape[n] (次元の要素数

In [37]:
x.shape[0]

NameError: name 'x' is not defined

#### 算術計算

##### 四則演算

###### 準備

In [47]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])

###### 要素ごとの足し算

In [48]:
x+y

array([3., 6., 9.])

###### 要素ごとの引き算

In [49]:
x-y

array([-1., -2., -3.])

###### 要素ごとの掛け算

In [50]:
x*y

array([ 2.,  8., 18.])

###### 要素ごとの割り算

In [51]:
x/y

array([0.5, 0.5, 0.5])

##### その他の計算

###### 準備

In [54]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 平方根の計算

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

###### ネイピア数（自然対数の底）e を底とする累乗

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### 統計計算

##### 標準正規分布

In [71]:
x=np.random.randn(10)
x

array([ 0.34297118, -0.86186092, -0.12782263, -0.30928826,  0.7070592 ,
       -0.03601683, -0.14301001,  0.99977137, -0.63565256,  0.91219328])

##### 符号

In [72]:
np.sign(x)

array([ 1., -1., -1., -1.,  1., -1., -1.,  1., -1.,  1.])

##### 平均（標準正規分布で要素数を増やすと０に近づく

In [73]:
x.mean()

0.08483438108916921

##### 標準偏差（標準正規分布で要素数を増やすと１に近づく

In [74]:
x.std()

0.6048006238110124

## N次配列操作
- ２次配列は行列とも呼ばれる。
- ３次元以上の配列を、テンソル/多次元配列と呼ぶ。

### 生成

#### 通常

In [22]:
a=np.array([[1,2],[3,4],[5,6]])

#### 型指定

In [30]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.int32)

#### 表示

##### 生

In [31]:
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

##### print

In [32]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


##### その他の関数

###### ndim (行列の次元は１次元

In [33]:
np.ndim(a)

2

###### shape (次元の形状

In [34]:
a.shape

(3, 2)

###### shape[n] (次元の要素数

In [35]:
a.shape[0]

3

###### dtype (列要素のデータ型

In [36]:
a.dtype

dtype('int32')