# NumPyのトレーニング♨

## 参考
開発基盤部会 Wiki
- NumPy  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?NumPy

## 準備

### インストール

In [1]:
!pip install numpy

### インポート

In [2]:
import numpy as np

## 配列操作
配列はベクトルとも呼ばれる。

### 生成

#### array

In [3]:
np.array([1.0,2.0,3.0])

array([1., 2., 3.])

#### arange

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ones（一埋

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### zeros（零埋

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### ランダム

##### empty

In [7]:
np.empty(5)

array([4.67614311e-310, 0.00000000e+000, 4.67614266e-310, 4.67614266e-310,
       2.37151510e-322])

##### random.randn（標準正規分布

In [8]:
np.random.randn(10)

array([ 2.86542959, -0.61172398,  1.53642686, -1.06627388, -0.98654513,
       -1.48014417, -1.08588623, -0.46598757,  1.24314207, -0.84108739])

#### 表示

In [9]:
a=np.array([1.0,2.0,3.0])

##### 生

In [10]:
a

array([1., 2., 3.])

##### print

In [11]:
print(a)

[1. 2. 3.]


##### その他の関数

###### type (型

In [12]:
type(a)

numpy.ndarray

###### dtype (列要素のデータ型

In [13]:
a.dtype

dtype('float64')

###### ndim (配列の次元は１次元

In [14]:
np.ndim(a)

1

###### shape (次元の形状

In [15]:
a.shape

(3,)

###### shape[n] (次元の要素数

In [16]:
a.shape[0]

3

#### 算術計算

##### 四則演算
２つのNumPy配列を算術計算で処理する。

###### 準備

In [17]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])

###### 同じ数の要素を持つ配列の要素ごとの計算

In [18]:
# 要素ごとの足し算
x+y

array([3., 6., 9.])

In [19]:
# 要素ごとの引き算
x-y

array([-1., -2., -3.])

In [20]:
# 要素ごとの掛け算
x*y

array([ 2.,  8., 18.])

In [21]:
# 要素ごとの割り算
x/y

array([0.5, 0.5, 0.5])

###### ブロード・キャストによる計算

In [22]:
# ブロード・キャストの割り算
x/2.0

array([0.5, 1. , 1.5])

##### その他の計算

###### 準備

In [23]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 平方根の計算

In [24]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

###### ネイピア数（自然対数の底）e を底とする累乗

In [25]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### 統計計算

##### 準備
（標準正規分布）

In [26]:
x=np.random.randn(10)
x

array([-0.08247059,  0.02854926, -1.08031377, -1.38516572,  0.56097479,
        0.4119746 ,  0.50972736, -0.36097456, -0.44924984,  0.85517121])

##### 符号

In [27]:
np.sign(x)

array([-1.,  1., -1., -1.,  1.,  1.,  1., -1., -1.,  1.])

##### 平均
標準正規分布で要素数を増やすと０に近づく

In [28]:
x.mean()

-0.09917772554215352

##### 標準偏差
標準正規分布で要素数を増やすと１に近づく

In [29]:
x.std()

0.693015135039021

## N次配列操作
- ２次配列は行列とも呼ばれる。
- ３次元以上の配列を、テンソル / 多次元配列と呼ぶ。

### 生成

#### 通常

In [30]:
a=np.array([[1,2],[3,4],[5,6]])

#### 型指定

In [31]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.int32)

#### 表示

##### 生

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

##### print

In [33]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


##### その他の関数

###### type (型

In [34]:
type(a)

numpy.ndarray

###### dtype (列要素のデータ型

In [35]:
a.dtype

dtype('int32')

###### ndim (行列の次元は２次元

In [36]:
np.ndim(a)

2

###### shape (次元の形状 (行, 列

In [37]:
a.shape

(3, 2)

###### shape[n] (次元の要素数 (行の数

In [38]:
a.shape[0]

3

#### 算術計算

##### 四則演算
２つのNumPy行列を算術計算で処理する。

###### 要素ごとの足し算

In [39]:
# 行列数が同じ
x=np.array([[1, 2], [3, 4]])
y=np.array([[3, 0], [0, 6]])
x+y

array([[ 4,  2],
       [ 3, 10]])

In [40]:
# 行列数が異なる（ブロード・キャスト）
x=np.array([[1, 2], [3, 4]])
y=np.array([10,20])
x+y

array([[11, 22],
       [13, 24]])

###### 要素ごとの掛け算
※ 行列の積ではないので注意。

In [41]:
# 行列数が同じ
x=np.array([[1, 2], [3, 4]])
y=np.array([[3, 0], [0, 6]])
x*y

array([[ 3,  0],
       [ 0, 24]])

In [42]:
# 行列数が異なる（ブロード・キャスト）
x=np.array([[1, 2], [3, 4]])
y=np.array([10,20])
x*y

array([[10, 40],
       [30, 80]])

##### その他の計算
[配列（ベクトル）の "算術計算 > その他の計算"](#その他の計算) と同じように計算できなかった。  
ベクトルを行列に変換して計算してみると良い（結果がエラーになる）。

#### 統計計算
[配列（ベクトル）の統計計算](#統計計算)と同じように計算できる。  
ベクトルを行列に変換して計算してみると良い（結果が同じになる）。

##### 配列

In [43]:
x=np.random.randn(12)
print(x)
print(np.sign(x))
print(x.mean())
print(x.std())

[ 1.156292    0.31623131  0.34444516  0.4064641   1.18572526 -0.59975787
 -0.52354892 -0.64787833 -1.26701141 -0.73760025  0.27605587  0.09389359]
[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1.  1.  1.]
0.0002758766216460114
0.7311387621574437


##### 行列

In [44]:
x=np.reshape(x,[4,3]) # ベクトルを行列に変換（後述
print(x)
print(np.sign(x))
print(x.mean())
print(x.std())

[[ 1.156292    0.31623131  0.34444516]
 [ 0.4064641   1.18572526 -0.59975787]
 [-0.52354892 -0.64787833 -1.26701141]
 [-0.73760025  0.27605587  0.09389359]]
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1. -1. -1.]
 [-1.  1.  1.]]
0.0002758766216460114
0.7311387621574437


## 要素へのアクセス

### 準備

#### 配列

In [45]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 行列

In [46]:
b=np.array([[51, 55], [14, 19], [0, 4]])
print(b)

[[51 55]
 [14 19]
 [ 0  4]]


### インデックス

#### 配列

In [47]:
a[1]

1

#### 行列

In [48]:
# N次配列にN個のインデックスを指定すると要素が取り出せる。
b[0][1] # 0行1列（スカラ

55

In [49]:
# N次配列にX個のインデックスを指定するとN-X次配列が取り出せる。
b[0]    # 0行

array([51, 55])

### 抽出

#### 配列

##### スライシング

In [50]:
a[3:7]

array([3, 4, 5, 6])

##### 配列でインデックスを指定

In [51]:
a[np.array([3,4,5,6])]

array([3, 4, 5, 6])

##### 比較演算

###### 条件に合う値を抽出

In [52]:
a[a==5]

array([5])

###### 5より大きい値を抽出。

In [53]:
a[a>5]

array([6, 7, 8, 9])

#### 行列

##### スライシング

In [54]:
b[0,1:2]

array([55])

In [55]:
b[1:2,0]

array([14])

##### 配列で行インデックスを指定

In [56]:
b[np.array([0,1])]

array([[51, 55],
       [14, 19]])

##### 比較演算

###### 15より大きい値を抽出。

In [57]:
b[b>15]

array([51, 55, 19])

###### 列値が条件に合う行を抽出

In [58]:
b[b[:,1]==19]

array([[14, 19]])

### 置換

#### 配列

##### 比較演算

###### 5より大きい値を調査。
[抽出](#抽出)の比較演算では、この配列をインデックスとして使っている。

In [59]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

###### 特定の値を変換

In [60]:
print(a)
a[a==5]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 6 7 8 9]


##### 型の置換

In [61]:
print(b.dtype)
b=np.array(b,dtype=np.int32) # 要素の型をint32に変換
print(b.dtype)

int64
int32


#### 行列

##### 比較演算

###### 15より大きい値を調査。

In [62]:
b>15

array([[ True,  True],
       [False,  True],
       [False, False]])

###### 特定の値を変換

In [63]:
print(b)
b[b==55]=99
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[51 99]
 [14 19]
 [ 0  4]]


##### 型の置換

In [64]:
print(b.dtype)
b=np.array(b,dtype=np.int64) # 要素の型をint64に変換
print(b.dtype)

int32
int64


## 編集

### 配列・行列変換

#### ２次配列の１次配列化

In [65]:
a=np.array([[51, 55], [14, 19], [0, 4]])
print(a)

[[51 55]
 [14 19]
 [ 0  4]]


##### 平坦化

In [66]:
b=a.flatten()
print(b)

[51 55 14 19  0  4]


##### 行ベクトル（横ベクトル）化

In [67]:
b=a[0,:] # 1行目、全列スライス
print(b)

[51 55]


##### 列ベクトル（縦ベクトル）化

In [68]:
b=a[:,0] # 1列目、全行スライス
print(b)

[51 14  0]


#### １次元配列の２次元配列化
（機械学習ライブラリ入力用）

##### １行ｎ列化

###### reshape

In [69]:
c=b.reshape(1, -1) # 1行3列 (3は自動計算
print(c)

[[51 14  0]]


###### np.newaxis

In [70]:
c=b[np.newaxis, :] # 1行3列 (3は自動計算
print(c)

[[51 14  0]]


##### ｎ行１列化

###### reshape

In [71]:
c=b.reshape(-1, 1) # 3行1列 (3は自動計算
print(c)

[[51]
 [14]
 [ 0]]


###### np.newaxis

In [72]:
c=b[:, np.newaxis] # 1行3列 (3は自動計算
print(c)

[[51]
 [14]
 [ 0]]


#### ２次元配列の１次元配列化
（機械学習ライブラリ入力用）

##### flatten

In [73]:
c.flatten()

array([51, 14,  0])

##### reshape

In [74]:
c.reshape(-1)

array([51, 14,  0])

### 行追加

In [75]:
a=np.array([[51, 55], [14, 19], [0, 4]])
print(a)

[[51 55]
 [14 19]
 [ 0  4]]


#### vstack
2次元で言うと、垂直方向＝行方向

In [76]:
np.vstack([a, a])

array([[51, 55],
       [14, 19],
       [ 0,  4],
       [51, 55],
       [14, 19],
       [ 0,  4]])

#### concatenate
０次元目（行）方向に結合

In [77]:
np.concatenate([a, a])
np.concatenate([a, a], 0)

array([[51, 55],
       [14, 19],
       [ 0,  4],
       [51, 55],
       [14, 19],
       [ 0,  4]])

### 列追加

#### hstack
2次元でいうと、水平方向＝列方向にスタック

In [78]:
np.hstack([a, a])

array([[51, 55, 51, 55],
       [14, 19, 14, 19],
       [ 0,  4,  0,  4]])

#### concatenate
１次元目（列）方向に結合

In [79]:
np.concatenate([a, a], 1)

array([[51, 55, 51, 55],
       [14, 19, 14, 19],
       [ 0,  4,  0,  4]])

### 行削除
≒ スライシング

In [80]:
a[0:2, :]

array([[51, 55],
       [14, 19]])

### 列の削除
≒ スライシング

In [81]:
a[:, 0:1]

array([[51],
       [14],
       [ 0]])

### 要素の追加

#### 新規次元を追加してスタック

##### ベクトル要素が新規次元で（行方向に）スタックして新規次元を追加

In [82]:
np.stack([a.flatten(), a.flatten()])
np.stack([a.flatten(), a.flatten()], 0)

array([[51, 55, 14, 19,  0,  4],
       [51, 55, 14, 19,  0,  4]])

##### 行列の要素が新規次元でスタックして新規次元を追加

In [83]:
np.stack([a, a])
np.stack([a, a], 0)

array([[[51, 55],
        [14, 19],
        [ 0,  4]],

       [[51, 55],
        [14, 19],
        [ 0,  4]]])

#### 既存の次元でスタックして次元を追加

##### ベクトル要素が列の次元で（列方向に）スタックして新規次元を追加

In [84]:
np.stack([a.flatten(), a.flatten()], 1)

array([[51, 51],
       [55, 55],
       [14, 14],
       [19, 19],
       [ 0,  0],
       [ 4,  4]])

##### 行列の要素が行の次元でスタックして新規次元を追加

In [85]:
np.stack([a, a], 1)

array([[[51, 55],
        [51, 55]],

       [[14, 19],
        [14, 19]],

       [[ 0,  4],
        [ 0,  4]]])

##### 行列の要素が列の次元でスタックして新規次元を追加

In [86]:
np.stack([a, a], 2)

array([[[51, 51],
        [55, 55]],

       [[14, 14],
        [19, 19]],

       [[ 0,  0],
        [ 4,  4]]])

## 型の変換

### LIST ⇔ NP型変換

#### LIST → NP
[生成](#生成)のところで説明済み。

#### LIST ← NP
ndarray.tolist()メソッドが使える。

In [87]:
a.tolist()

[[51, 55], [14, 19], [0, 4]]

### NP ⇔ DF型変換
PandasTrainingで説明する。

## 行列の変換

### 転置行列

#### Tプロパティ

In [88]:
print(a.T)

[[51 14  0]
 [55 19  4]]


#### transposeメソッド

In [89]:
print(a.transpose())

[[51 14  0]
 [55 19  4]]


### 次元の入れ替え
transposeを使うと柔軟な対応が可能

#### 行列（２次元配列

In [90]:
a.transpose([1, 0])

array([[51, 14,  0],
       [55, 19,  4]])

#### ３次元配列

In [91]:
np.stack([a, a]).transpose([0,1,2])

array([[[51, 55],
        [14, 19],
        [ 0,  4]],

       [[51, 55],
        [14, 19],
        [ 0,  4]]])

In [92]:
np.stack([a, a]).transpose([2,1,0])

array([[[51, 51],
        [14, 14],
        [ 0,  0]],

       [[55, 55],
        [19, 19],
        [ 4,  4]]])

### reshape
コチラは入れ替えではなく、再構成。

#### 準備

In [93]:
a=np.arange(0, 12)

#### numpy.reshape

In [94]:
np.reshape(a,[4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
np.reshape(a,[3,2,2]) 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### ndarray.reshape

In [96]:
a.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
a.reshape([3,2,2]) 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## One-Hotエンコーディング

### 準備

In [98]:
a=np.array([[0,1,2,3,4,5,6,7,8,9]])
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### エンコーディング

#### np_utils.to_categoricalを使う。

In [99]:
# Kerasのライブラリらしい。
# b = np_utils.to_categorical(a, num_classes=10).astype('i') 

#### np.identityを使う。

In [100]:
b = np.identity(10)[a].astype('i')
b

array([[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], dtype=int32)

### デコーディング

In [101]:
c=b.argmax(axis=1)
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## ベクトルの積算（内積）

### データの生成

In [114]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

In [115]:
a=a.reshape(1, -1)
b=b.reshape(1, -1).T # 転置行列に

In [116]:
print("a")
print(a)
print("b")
print(b)

a
[[1 2 3 4]]
b
[[10]
 [20]
 [30]
 [40]]


### 計算方法

#### 演算子

In [117]:
a@b

array([[300]])

#### メソッド

In [118]:
np.dot(a,b)

array([[300]])

### 交換法則が成立
行列では、交換法則の不成立になるが、  
ベクトルの場合は成立する（ただし転置が必要）。

#### 演算子

In [121]:
a@b

array([[300]])

In [122]:
b.T@a.T

array([[300]])

#### メソッド

In [123]:
np.dot(a,b)

array([[300]])

In [124]:
np.dot(b.T,a.T)

array([[300]])

## 行列の積算

### データ生成

In [102]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
c=np.array([[1,2],[3,4]])
d=np.array([7,8])

print("a")
print(a)
print("b")
print(b)
print("c")
print(c)
print("d")
print(d)

a
[[1 2 3]
 [4 5 6]]
b
[[1 2]
 [3 4]
 [5 6]]
c
[[1 2]
 [3 4]]
d
[7 8]


### 計算方法 
[要素ごとの掛け算](#要素ごとの掛け算)でないことに注意。

#### 演算子
@（ドット積）演算子を使用する。

In [103]:
a@b

array([[22, 28],
       [49, 64]])

In [104]:
b@c

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [105]:
b@d

array([23, 53, 83])

In [107]:
#a@c # Ａ行列の列数とＢ行列の行数が一致しない。

#### メソッド

In [108]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [109]:
np.dot(b,c)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [110]:
np.dot(b,d)

array([23, 53, 83])

In [112]:
#np.dot(a,c) # Ａ行列の列数とＢ行列の行数が一致しない。