# NumPyのトレーニング♨
配列はベクトルとも呼ばれる（→ [行列](NumPyTraining2.ipynb)）。

## [目次](TableOfContents.ipynb)
- [環境準備](#環境準備)
  - [インストール](#インストール)
  - [インポート](#インポート)
- [操作](#操作)
  - [生成](#生成)
  - [コピー](#コピー)
  - [表示](#表示)
- [計算](#計算)
  - [算術計算](#算術計算)
  - [統計計算](#統計計算)
- [アクセス](#アクセス)
  - [インデックス番号で指定](#インデックス番号で指定)
  - [複数要素の抽出](#複数要素の抽出)
  - [複数要素の置換](#複数要素の置換)
- [ベクトルの積算（内積）](#ベクトルの積算（内積）)
  - [データ生成](#データ生成)
  - [計算方法](#計算方法)
  - [交換法則](#交換法則)
  
## 参考
開発基盤部会 Wiki
- NumPy  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?NumPy

## 環境準備

### インストール

In [ ]:
!pip install numpy

### インポート

In [2]:
import numpy as np

In [3]:
import warnings
warnings.filterwarnings('ignore')

## 操作

### 生成

#### array

In [4]:
np.array([1.0,2.0,3.0])

array([1., 2., 3.])

#### arange

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ones（一埋

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### zeros（零埋

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### ランダム

##### empty

In [8]:
np.empty(5)

array([1.14336051e-313, 0.00000000e+000, 4.68320462e-310, 4.68320465e-310,
       2.37151510e-322])

##### random.randn（標準正規分布

In [9]:
np.random.randn(10)

array([-0.2205409 , -0.05504664, -1.34047278, -0.78326938,  0.26394595,
       -0.52620167, -0.86969645,  1.2524427 , -1.81822665, -0.01517474])

### コピー

#### 以下は参照渡し

In [10]:
a=np.array([1.0,2.0,3.0])
b=a
b[1]=100
print(a)
print(b)

[  1. 100.   3.]
[  1. 100.   3.]


#### コピーする場合は以下

In [11]:
a=np.array([1.0,2.0,3.0])
b=a.copy()
b[1]=100
print(a)
print(b)

[1. 2. 3.]
[  1. 100.   3.]


### 表示

In [12]:
a=np.array([1.0,2.0,3.0])

#### 生

In [13]:
a

array([1., 2., 3.])

#### print

In [14]:
print(a)

[1. 2. 3.]


#### その他の関数

##### type
変数のデータ型

In [15]:
type(a)

numpy.ndarray

##### dtype
要素のデータ型

In [16]:
a.dtype

dtype('float64')

##### ndim
配列の次元は１次元

In [17]:
np.ndim(a)

1

##### shape
次元の形状

In [18]:
a.shape

(3,)

##### shape[n]
ｎ次元の要素数

In [19]:
a.shape[0]

3

## 計算

### 算術計算

#### 四則演算
２つのNumPy配列を算術計算で処理する。

##### 準備

In [20]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])

##### 同じ数の要素を持つ配列の要素ごとの計算

###### 要素ごとの足し算

In [21]:
x+y

array([3., 6., 9.])

###### 要素ごとの引き算

In [22]:
x-y

array([-1., -2., -3.])

###### 要素ごとの掛け算

In [23]:
x*y

array([ 2.,  8., 18.])

###### 要素ごとの割り算

In [24]:
x/y

array([0.5, 0.5, 0.5])

##### ブロード・キャストによる計算

In [25]:
# ブロード・キャストの割り算
x/2.0

array([0.5, 1. , 1.5])

#### その他の計算

##### 準備

In [26]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 平方根の計算

In [27]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

##### ネイピア数（自然対数の底）e を底とする累乗

In [28]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### 統計計算

#### 準備
（標準正規分布）

In [29]:
x=np.random.rand(10)
print(x)

[0.65829429 0.10913517 0.24321879 0.30499759 0.87907537 0.03563249
 0.1049293  0.55851045 0.20243893 0.99833394]


#### 符号

In [30]:
np.sign(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 平均値
標準正規分布で要素数を増やすと０に近づく

In [31]:
x.mean()

np.float64(0.4094566327189223)

#### 中央値

In [32]:
np.median(x)

np.float64(0.27410819089813254)

#### 標準偏差
標準正規分布で要素数を増やすと１に近づく

In [33]:
x.std()

np.float64(0.324889652674455)

## アクセス
要素へのアクセス

### 準備

In [34]:
def function1():
    return np.arange(10)

In [35]:
a=function1()
print(a)

[0 1 2 3 4 5 6 7 8 9]


### インデックス番号で指定

In [36]:
a[1]

np.int64(1)

### 複数要素の抽出 

#### スライシング

In [37]:
a[3:7]

array([3, 4, 5, 6])

#### 配列で指定

In [38]:
a[np.array([3,4,5,6])]

array([3, 4, 5, 6])

#### 比較演算で指定
比較の結果boolの配列が生成され、これでインデックスを指定している。

##### 「＝」で指定

###### True, False配列を取得

In [39]:
a==5

array([False, False, False, False, False,  True, False, False, False,
       False])

###### True, False配列で抽出

In [40]:
a[a==5]

array([5])

##### 「＞」で指定

###### True, False配列を取得

In [41]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

###### True, False配列で抽出

In [42]:
a[a>5]

array([6, 7, 8, 9])

### 複数要素の置換

#### スライシング

In [43]:
a=function1()
print(a)
a[3:7]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 0 0 0 0 7 8 9]


#### 配列で指定

In [44]:
a=function1()
print(a)
a[np.array([3,4,5,6])]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 0 0 0 0 7 8 9]


##### 「＝」で指定

###### True, False配列を取得

In [45]:
a=function1()
a==5

array([False, False, False, False, False,  True, False, False, False,
       False])

###### True, False配列で置換

In [46]:
print(a)
a[a==5]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 6 7 8 9]


##### 「＞」で指定

###### True, False配列を取得

In [47]:
a=function1()
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

###### True, False配列で置換

In [48]:
print(a)
a[a>5]=0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 0 0 0 0]


## ベクトルの積算（内積）

### データ生成

#### 生成

In [49]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

#### 確認

In [50]:
print("a")
print(a)
print("b")
print(b)

a
[1 2 3 4]
b
[10 20 30 40]


### 計算方法

#### 演算子

In [51]:
a@b

np.int64(300)

#### メソッド

In [52]:
np.dot(a,b)

np.int64(300)

### 交換法則
行列では、交換法則の不成立になるが、ベクトルの場合は成立する。

#### 演算子

In [53]:
a@b

np.int64(300)

In [54]:
b@a

np.int64(300)

#### メソッド

In [55]:
np.dot(a,b)

np.int64(300)

In [56]:
np.dot(b,a)

np.int64(300)