# NumPyのトレーニング♨
行列（→ [配列（ベクトル）](NumPyTraining1.ipynb)）。
  
## [目次](TableOfContents.ipynb)
- [環境準備](#環境準備)
- [操作](#操作)
  - [生成](#生成)
  - [コピー](#コピー)
  - [表示](#表示)
- [計算](#計算)
  - [算術計算](#算術計算)
  - [統計計算](#統計計算)
- [アクセス](#アクセス)
  - [インデックス番号で指定](#インデックス番号で指定)
  - [複数要素の抽出](#複数要素の抽出)
  - [複数要素の置換](#複数要素の置換)
- [行列の積算（ドット積）](#行列の積算（ドット積）)
  - [データ生成](#データ生成)
  - [計算方法](#計算方法)
  - [交換法則](#交換法則)
  
## 参考
開発基盤部会 Wiki
- NumPy  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?NumPy

## [環境準備](NumPyTraining1.ipynb)

In [1]:
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

## 操作
２次元テンソルは行列とも呼ばれる。

### 生成

#### 通常

In [3]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 型指定

In [4]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.int32)
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

### コピー

#### 以下は参照渡し

In [5]:
a=np.array([[1,2],[3,4],[5,6]])
b=a
b[1,1]=100
print(a)
print(b)

[[  1   2]
 [  3 100]
 [  5   6]]
[[  1   2]
 [  3 100]
 [  5   6]]


#### コピーする場合は以下

In [6]:
a=np.array([[1,2],[3,4],[5,6]])
b=a.copy()
b[1,1]=100
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[  1   2]
 [  3 100]
 [  5   6]]


### 表示

#### 生

In [7]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

#### print

In [8]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


#### その他の関数

##### type (型

In [9]:
type(a)

numpy.ndarray

##### dtype
要素のデータ型

In [10]:
a.dtype

dtype('int64')

##### ndim
行列の次元は２次元

In [11]:
np.ndim(a)

2

##### shape
次元の形状 (行数, 列数

In [12]:
a.shape

(3, 2)

##### shape[n] 
ｎ次元の要素数（０：行数、１：列数

In [13]:
a.shape[0]

3

## 計算

### 算術計算

#### 四則演算
２つのNumPy行列を算術計算で処理する。

##### 要素ごとの足し算

###### 行列数が同じ

In [14]:
x=np.array([[1, 2], [3, 4]])
y=np.array([[3, 0], [0, 6]])
x+y

array([[ 4,  2],
       [ 3, 10]])

###### 行列数が異なる（ブロード・キャスト）

In [15]:
x=np.array([[1, 2], [3, 4]])
y=np.array([10,20])
x+y

array([[11, 22],
       [13, 24]])

##### 要素ごとの掛け算
※ 行列の積ではないので注意。

###### 行列数が同じ

In [16]:
x=np.array([[1, 2], [3, 4]])
y=np.array([[3, 0], [0, 6]])
x*y

array([[ 3,  0],
       [ 0, 24]])

###### 行列数が異なる（ブロード・キャスト）

In [17]:
x=np.array([[1, 2], [3, 4]])
y=np.array([10,20])
x*y

array([[10, 40],
       [30, 80]])

#### その他の計算
[配列（ベクトル）の "算術計算 > その他の計算"](NumPyTraining1.ipynb) と同じように計算できなかった。  
ベクトルを行列に変換して計算してみると良い（結果がエラーになる）。

### 統計計算
[配列（ベクトル）の統計計算](NumPyTraining1.ipynb)と同じように計算できる。  
ベクトルを行列に変換して計算してみると良い（結果が同じになる）。

#### 準備
（標準正規分布）

In [18]:
x=np.random.randn(12)
x=np.reshape(x,[4,3]) # ベクトルを行列に変換（後述
print(x)

[[ 1.25544935 -1.11541626  2.30541631]
 [-0.78433206 -1.77866106  0.47138806]
 [-1.09904526  1.4424425  -0.75359868]
 [-1.0096699  -1.80410616 -0.23108525]]


#### 符号

In [19]:
print(np.sign(x))

[[ 1. -1.  1.]
 [-1. -1.  1.]
 [-1.  1. -1.]
 [-1. -1. -1.]]


#### 平均値
標準正規分布で要素数を増やすと０に近づく

In [20]:
print(x.mean())

-0.25843486708867297


#### 中央値

In [21]:
np.median(x)

np.float64(-0.7689653676546311)

#### 標準偏差
標準正規分布で要素数を増やすと１に近づく

In [22]:
print(x.std())

1.2753722031884118


## アクセス
要素へのアクセス

### 準備

In [23]:
def function1():
    return np.array([[51, 55], [14, 19], [0, 4]])

In [24]:
b=function1()
print(b)

[[51 55]
 [14 19]
 [ 0  4]]


### インデックス番号で指定

##### N次元配列にN個のインデックスを指定すると要素が取り出せる。

In [25]:
b[0][1] # 0行1列（スカラ

np.int64(55)

##### N次元配列にX個のインデックスを指定するとN-X次元配列が取り出せる。

In [26]:
b[0]    # 0行の行ベクトル

array([51, 55])

### 複数要素の抽出 

#### スライシング

##### 列をスライシングで指定

In [27]:
b[0,1:2]

array([55])

##### 行をスライシングで指定

In [28]:
b[1:2,0]

array([14])

#### 配列で指定

##### 行インデックス

In [29]:
b[np.array([0,1])]

array([[51, 55],
       [14, 19]])

##### 行＆列インデックス

In [30]:
b[np.array([0,1]),np.array([1])]

array([55, 19])

#### 比較演算で指定
比較の結果boolの配列や行列が生成され、これでインデックスを指定している。

##### 「＝」で指定

###### True, False行列を取得

In [31]:
b==19

array([[False, False],
       [False,  True],
       [False, False]])

###### True, False行列で抽出

In [32]:
b[b==19]

array([19])

##### 「＞」で指定

###### True, False行列を取得

In [33]:
b>15

array([[ True,  True],
       [False,  True],
       [False, False]])

###### True, False行列で抽出

In [34]:
b[b>15]

array([51, 55, 19])

### 複数要素の置換

#### スライシング

##### 列をスライシングで指定

In [35]:
b=function1()
print(b)
b[0,1:2]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[51  0]
 [14 19]
 [ 0  4]]


##### 行をスライシングで指定

In [36]:
b=function1()
print(b)
b[1:2,0]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[51 55]
 [ 0 19]
 [ 0  4]]


#### 配列で指定

##### 行インデックス

In [37]:
b=function1()
print(b)
b[np.array([0,1])]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[0 0]
 [0 0]
 [0 4]]


##### 行＆列インデックス

In [38]:
b=function1()
print(b)
b[np.array([0,1]),np.array([1])]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[51  0]
 [14  0]
 [ 0  4]]


#### 比較演算で指定
比較の結果boolの行列が生成され、これでインデックスを指定している。

##### 「＝」で指定

###### True, False行列を取得

In [39]:
b=function1()
b==19

array([[False, False],
       [False,  True],
       [False, False]])

###### True, False行列で置換

In [40]:
print(b)
b[b==19]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[51 55]
 [14  0]
 [ 0  4]]


##### 「＞」で指定

###### True, False行列を取得

In [41]:
b=function1()
b>5

array([[ True,  True],
       [ True,  True],
       [False, False]])

###### True, False行列で置換

In [42]:
print(b)
b[b>5]=0
print(b)

[[51 55]
 [14 19]
 [ 0  4]]
[[0 0]
 [0 0]
 [0 4]]


## 行列の積算（ドット積）

### データ生成

In [43]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
c=np.array([[1,2],[3,4]])
d=np.array([7,8])

print("a")
print(a)
print("b")
print(b)
print("c")
print(c)
print("d")
print(d)

a
[[1 2 3]
 [4 5 6]]
b
[[1 2]
 [3 4]
 [5 6]]
c
[[1 2]
 [3 4]]
d
[7 8]


### 計算方法 
- [要素ごとの掛け算](#要素ごとの掛け算)でないことに注意。
- Ａ行列 * Ｂ行列 = Ｃ行列
  - Ａ行列の列数とＢ行列の行数が一致ししている必要がある。
  - 計算後のＣ行列は、Ａ行列の行数 * Ｂ行列の列数の行列になる。

#### 演算子
@（ドット積）演算子を使用する。

In [44]:
a@b

array([[22, 28],
       [49, 64]])

In [45]:
b@c

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [46]:
b@d # 行列と配列は列数一致で行数の配列になる。

array([23, 53, 83])

In [47]:
#a@c # Ａ行列の列数とＢ行列の行数が一致しない。

#### メソッド

In [48]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [49]:
np.dot(b,c)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [50]:
np.dot(b,d) # 行列と配列は列数一致で行数の配列になる。

array([23, 53, 83])

In [51]:
#np.dot(a,c) # Ａ行列の列数とＢ行列の行数が一致しない。

### 交換法則
行列では、交換法則の不成立になるが、転置すれば成立する。

#### 演算子

In [52]:
a@b

array([[22, 28],
       [49, 64]])

In [53]:
(b.T@a.T).T

array([[22, 28],
       [49, 64]])

#### メソッド

In [54]:
np.dot(b,c)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [55]:
np.dot(c.T,b.T).T

array([[ 7, 10],
       [15, 22],
       [23, 34]])